#!/bin/bash

# basic for loop; using variable to hold a list

list="Alabama Alaska Arizona Arkansas Colorado"
list=$list" Connecticut"
for state in $list; do
  echo "Have you ever visited $state?"
done
